name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      # Install NPM dependencies, cache them correctly
      - name: npm install, build and test
        with: 
          run: npm install
               npm run build --if-present
               npm test
 
