name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      # Install NPM dependencies, cache them correctly
      - name: npm install, build and test
        uses: ng-easy/npm-setup@v1.7.2
        
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: firefox
          build: npm run build
          start: npm start
